VERSION = '1.0.1f'
VERSION = VERSION + '-FULL'
def set_globals(self):
    self.VERSION = VERSION
    self.F_QUIT_BUTTON = True
    self.F_SKIP_TUTORIAL = False
    self.F_BASIC_CREDITS = False
    self.F_EXTERNAL_LINKS = True
    self.F_ENABLE_PERF_OVERLAY = False
    self.F_NO_SAVING = False
    self.F_MUTE = False
    self.F_SOUND_THREAD = True
    self.F_VIDEO_SETTINGS = True
    self.F_CTA = False
    self.F_VERBOSE = True
    self.F_HTTP_SCORES = False
    self.F_RUMBLE = 'None'
    self.F_CRASH_REPORTS = False
    self.F_NO_ERROR_HAND = False
    self.F_SWAP_AB_PIPS = False
    self.F_SWAP_AB_BUTTONS = False
    self.F_SWAP_XY_BUTTONS = False
    self.F_NO_ACHIEVEMENTS = False
    self.F_DISP_USERNAME = 'None'
    self.F_ENGLISH_ONLY = 'None'
    self.F_GUIDE = False
    self.F_JAN_CTA = False
    self.F_HIDE_BG = False
    self.F_TROPHIES = False
    self.F_PS4_PLAYSTATION_GLYPHS = False
    self.F_LOCAL_CLIPBOARD = False
    self.F_SAVE_TIMER = 30
    self.F_MOBILE_UI = False
    self.F_HIDE_BETA_LANGS = 'None'
    if love.system.getOS() == 'Windows':
        self.F_DISCORD = True
        self.F_SAVE_TIMER = 5
        self.F_ENGLISH_ONLY = False
        self.F_CRASH_REPORTS = False
    if love.system.getOS() == 'OS X':
        self.F_SAVE_TIMER = 5
        self.F_DISCORD = True
        self.F_ENGLISH_ONLY = False
        self.F_CRASH_REPORTS = False
    if love.system.getOS() == 'Nintendo Switch':
        self.F_HIDE_BETA_LANGS = True
        self.F_BASIC_CREDITS = True
        self.F_NO_ERROR_HAND = True
        self.F_QUIT_BUTTON = False
        self.F_SKIP_TUTORIAL = False
        self.F_ENABLE_PERF_OVERLAY = False
        self.F_NO_SAVING = False
        self.F_MUTE = False
        self.F_SOUND_THREAD = True
        self.F_SWAP_AB_PIPS = True
        self.F_SWAP_AB_BUTTONS = False
        self.F_SWAP_XY_BUTTONS = True
        self.F_VIDEO_SETTINGS = False
        self.F_RUMBLE = 0.7
        self.F_CTA = False
        self.F_VERBOSE = False
        self.F_NO_ACHIEVEMENTS = True
        self.F_ENGLISH_ONLY = 'None'
        self.F_EXTERNAL_LINKS = False
        self.F_HIDE_BG = True
    if love.system.getOS() == 'ps4' if love.system.getOS() == 'ps4' else love.system.getOS() == 'ps5':
        self.F_HIDE_BETA_LANGS = True
        self.F_NO_ERROR_HAND = True
        self.F_QUIT_BUTTON = False
        self.F_SKIP_TUTORIAL = False
        self.F_ENABLE_PERF_OVERLAY = False
        self.F_NO_SAVING = False
        self.F_MUTE = False
        self.F_SOUND_THREAD = True
        self.F_VIDEO_SETTINGS = False
        self.F_RUMBLE = 0.5
        self.F_CTA = False
        self.F_VERBOSE = False
        self.F_GUIDE = True
        self.F_PS4_PLAYSTATION_GLYPHS = False
        self.F_EXTERNAL_LINKS = False
        self.F_HIDE_BG = True
    if love.system.getOS() == 'xbox':
        self.F_HIDE_BETA_LANGS = True
        self.F_NO_ERROR_HAND = True
        self.F_DISP_USERNAME = True
        self.F_SKIP_TUTORIAL = False
        self.F_ENABLE_PERF_OVERLAY = False
        self.F_NO_SAVING = False
        self.F_MUTE = False
        self.F_SOUND_THREAD = True
        self.F_VIDEO_SETTINGS = False
        self.F_RUMBLE = 1.0
        self.F_CTA = False
        self.F_VERBOSE = False
        self.F_EXTERNAL_LINKS = False
        self.F_HIDE_BG = True
    self.SEED = os.time()
    self.TIMERS = {'TOTAL': 0, 'REAL': 0, 'REAL_SHADER': 0, 'UPTIME': 0, 'BACKGROUND': 0}
    self.FRAMES = {'DRAW': 0, 'MOVE': 0}
    self.exp_times = {'xy': 0, 'scale': 0, 'r': 0}
    self.SETTINGS = {'COMP': {'name': '', 'prev_name': '', 'submission_name': 'None', 'score': 0}, 'DEMO': {'total_uptime': 0, 'timed_CTA_shown': False, 'win_CTA_shown': False, 'quit_CTA_shown': False}, 'ACHIEVEMENTS_EARNED': {}, 'crashreports': False, 'colourblind_option': False, 'language': 'en-us', 'screenshake': True, 'rumble': self.F_RUMBLE, 'play_button_pos': 2, 'GAMESPEED': 1, 'paused': False, 'SOUND': {'volume': 50, 'music_volume': 100, 'game_sounds_volume': 100}, 'WINDOW': {'screenmode': 'Borderless', 'vsync': 1, 'selected_display': 1, 'display_names': {1: '[NONE]'}, 'DISPLAYS': {1: {'name': '[NONE]', 'screen_res': {'w': 1000, 'h': 650}}}}, 'GRAPHICS': {'texture_scaling': 2, 'shadows': 'On', 'crt': 70, 'bloom': 1}}
    self.METRICS = {'cards': {'used': {}, 'bought': {}, 'appeared': {}}, 'decks': {'chosen': {}, 'win': {}, 'lose': {}}, 'bosses': {'faced': {}, 'win': {}, 'lose': {}}}
    self.PROFILES = {1: {}, 2: {}, 3: {}}
    self.TILESIZE = 20
    self.TILESCALE = 3.65
    self.TILE_W = 20
    self.TILE_H = 11.5
    self.DRAW_HASH_BUFF = 2
    self.CARD_W = 2.4 * 35 / 41
    self.CARD_H = 2.4 * 47 / 41
    self.HIGHLIGHT_H = 0.2 * self.CARD_H
    self.COLLISION_BUFFER = 0.05
    self.PITCH_MOD = 1
    self.STATES = {'SELECTING_HAND': 1, 'HAND_PLAYED': 2, 'DRAW_TO_HAND': 3, 'GAME_OVER': 4, 'SHOP': 5, 'PLAY_TAROT': 6, 'BLIND_SELECT': 7, 'ROUND_EVAL': 8, 'TAROT_PACK': 9, 'PLANET_PACK': 10, 'MENU': 11, 'TUTORIAL': 12, 'SPLASH': 13, 'SANDBOX': 14, 'SPECTRAL_PACK': 15, 'DEMO_CTA': 16, 'STANDARD_PACK': 17, 'BUFFOON_PACK': 18, 'NEW_ROUND': 19}
    self.STAGES = {'MAIN_MENU': 1, 'RUN': 2, 'SANDBOX': 3}
    self.STAGE_OBJECTS = {1: {}, 2: {}, 3: {}}
    self.STAGE = self.STAGES.MAIN_MENU
    self.STATE = self.STATES.SPLASH
    self.TAROT_INTERRUPT = 'None'
    self.STATE_COMPLETE = False
    self.ARGS = {}
    self.FUNCS = {}
    self.I = {'NODE': {}, 'MOVEABLE': {}, 'SPRITE': {}, 'UIBOX': {}, 'POPUP': {}, 'CARD': {}, 'CARDAREA': {}, 'ALERT': {}}
    self.ANIMATION_ATLAS = {}
    self.ASSET_ATLAS = {}
    self.MOVEABLES = {}
    self.ANIMATIONS = {}
    self.DRAW_HASH = {}
    self.MIN_CLICK_DIST = 0.9
    self.MIN_HOVER_TIME = 0.1
    self.DEBUG = False
    self.ANIMATION_FPS = 10
    self.VIBRATION = 0
    self.CHALLENGE_WINS = 5
    self.C = {'MULT': HEX(FE5F55), 'CHIPS': HEX(009dff), 'MONEY': HEX(f3b958), 'XMULT': HEX(FE5F55), 'FILTER': HEX(ff9a00), 'BLUE': HEX(009dff), 'RED': HEX(FE5F55), 'GREEN': HEX(4BC292), 'PALE_GREEN': HEX(56a887), 'ORANGE': HEX(fda200), 'IMPORTANT': HEX(ff9a00), 'GOLD': HEX(eac058), 'YELLOW': {1: 1, 2: 1, 3: 0, 4: 1}, 'CLEAR': {1: 0, 2: 0, 3: 0, 4: 0}, 'WHITE': {1: 1, 2: 1, 3: 1, 4: 1}, 'PURPLE': HEX(8867a5), 'BLACK': HEX(374244), 'L_BLACK': HEX(4f6367), 'GREY': HEX(5f7377), 'CHANCE': HEX(4BC292), 'JOKER_GREY': HEX(bfc7d5), 'VOUCHER': HEX(cb724c), 'BOOSTER': HEX(646eb7), 'EDITION': {1: 1, 2: 1, 3: 1, 4: 1}, 'DARK_EDITION': {1: 0, 2: 0, 3: 0, 4: 1}, 'ETERNAL': HEX(c75985), 'PERISHABLE': HEX(4f5da1), 'RENTAL': HEX(b18f43), 'DYN_UI': {'MAIN': HEX(374244), 'DARK': HEX(374244), 'BOSS_MAIN': HEX(374244), 'BOSS_DARK': HEX(374244), 'BOSS_PALE': HEX(374244)}, 'SO_1': {'Hearts': HEX(f03464), 'Diamonds': HEX(f06b3f), 'Spades': HEX(403995), 'Clubs': HEX(235955)}, 'SO_2': {'Hearts': HEX(f83b2f), 'Diamonds': HEX(e29000), 'Spades': HEX(4f31b9), 'Clubs': HEX(008ee6)}, 'SUITS': {'Hearts': HEX(FE5F55), 'Diamonds': HEX(FE5F55), 'Spades': HEX(374649), 'Clubs': HEX(424e54)}, 'UI': {'TEXT_LIGHT': {1: 1, 2: 1, 3: 1, 4: 1}, 'TEXT_DARK': HEX(4F6367), 'TEXT_INACTIVE': HEX(88888899), 'BACKGROUND_LIGHT': HEX(B8D8D8), 'BACKGROUND_WHITE': {1: 1, 2: 1, 3: 1, 4: 1}, 'BACKGROUND_DARK': HEX(7A9E9F), 'BACKGROUND_INACTIVE': HEX(666666FF), 'OUTLINE_LIGHT': HEX(D8D8D8), 'OUTLINE_LIGHT_TRANS': HEX(D8D8D866), 'OUTLINE_DARK': HEX(7A9E9F), 'TRANSPARENT_LIGHT': HEX(eeeeee22), 'TRANSPARENT_DARK': HEX(22222222), 'HOVER': HEX(00000055)}, 'SET': {'Default': HEX(cdd9dc), 'Enhanced': HEX(cdd9dc), 'Joker': HEX(424e54), 'Tarot': HEX(424e54), 'Planet': HEX(424e54), 'Spectral': HEX(424e54), 'Voucher': HEX(424e54)}, 'SECONDARY_SET': {'Default': HEX(9bb6bdFF), 'Enhanced': HEX(8389DDFF), 'Joker': HEX(708b91), 'Tarot': HEX(a782d1), 'Planet': HEX(13afce), 'Spectral': HEX(4584fa), 'Voucher': HEX(fd682b), 'Edition': HEX(4ca893)}, 'RARITY': {1: HEX(009dff), 2: HEX(4BC292), 3: HEX(fe5f55), 4: HEX(b26cbb)}, 'BLIND': {'Small': HEX(50846e), 'Big': HEX(50846e), 'Boss': HEX(b44430), 'won': HEX(4f6367)}, 'HAND_LEVELS': {1: HEX(efefef), 2: HEX(95acff), 3: HEX(65efaf), 4: HEX(fae37e), 5: HEX(ffc052), 6: HEX(f87d75), 7: HEX(caa0ef)}, 'BACKGROUND': {'L': {1: 1, 2: 1, 3: 0, 4: 1}, 'D': HEX(374244), 'C': HEX(374244), 'contrast': 1}}
    '0[G.C.HAND_LEVELS]' = G.C.RED
    G.C.UI_CHIPS = copy_table()
    G.C.UI_MULT = copy_table()
    self.UIT = {'T': 1, 'B': 2, 'C': 3, 'R': 4, 'O': 5, 'ROOT': 7, 'S': 8, 'I': 9, 'padding': 0}
    self.handlist = {1: 'Flush Five', 2: 'Flush House', 3: 'Five of a Kind', 4: 'Straight Flush', 5: 'Four of a Kind', 6: 'Full House', 7: 'Flush', 8: 'Straight', 9: 'Three of a Kind', 10: 'Two Pair', 11: 'Pair', 12: 'High Card'}
    self.button_mapping = {'a': G.F_SWAP_AB_BUTTONS & 'b' if G.F_SWAP_AB_BUTTONS & 'b' else 'None', 'b': G.F_SWAP_AB_BUTTONS & 'a' if G.F_SWAP_AB_BUTTONS & 'a' else 'None', 'y': G.F_SWAP_XY_BUTTONS & 'x' if G.F_SWAP_XY_BUTTONS & 'x' else 'None', 'x': G.F_SWAP_XY_BUTTONS & 'y' if G.F_SWAP_XY_BUTTONS & 'y' else 'None'}
    self.keybind_mapping = {1: {'a': 'dpleft', 'd': 'dpright', 'w': 'dpup', 's': 'dpdown', 'x': 'x', 'c': 'y', 'space': 'a', 'shift': 'b', 'esc': 'start', 'q': 'triggerleft', 'e': 'triggerright'}}
G = Game()