print(This is, _VERSION, running a script inside, 0[arg])
print(These are the arguments from varargs)
print(*args)
print(These are the arguments from arg)
for i in range(0, len(arg), ):print(i, i[arg])
print(These are the libraries)
for kv in pairs(_G):
    if type(v) == 'table':io.write(k, ,)
io.write(\n)
print(This is, _VERSION, running a script inside, 0[arg])